SELECT
	ORG_UNIT,
	FULL_NAME,
    SUM(clients_registered) AS clients_registered,
    SUM(SCREENINGS_DUE) AS SCREENINGS_DUE,
    SUM(SCREENINGS_OVERDUE) AS SCREENINGS_OVERDUE,
    SUM(CLIENTS_NOT_CONSENT_TO_SCREENING) AS CLIENTS_NOT_CONSENT_TO_SCREENING,
    SUM(SCREENING_NOT_REQUIRED) AS SCREENING_NOT_REQUIRED,
    SUM(CLIENTS_SCREENED) AS CLIENTS_SCREENED,
    SUM(CLIENTS_REFERRED) AS CLIENTS_REFERRED,
    SUM(CLIENTS_NOT_REFERRED) AS CLIENTS_NOT_REFERRED,
    SUM(CLIENT_VISITS) AS CLIENT_VISITS,
    SUM(PHONE_CALLS_DUE) AS PHONE_CALLS_DUE,
    SUM(PHONE_CALLS_OVERDUE) AS PHONE_CALLS_OVERDUE,
    SUM(HOME_VISITS_DUE) AS HOME_VISITS_DUE,
    SUM(HOME_VISITS_OVERDUE) AS HOME_VISITS_OVERDUE,
	CREATED_DATE,
	USER_ROLE,
	DSD
FROM view_do_performance
GROUP BY ORG_UNIT, FULL_NAME, USER_ROLE, DSD;